services:
  - type: web
    name: api-estudiantes
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: miclavejwt
      - key: MONGODB_URI
        value: mongodb+srv://kamus:UXYyHLbj8bhw4Cqi@cluster0.n7ejhiz.mongodb.net/estudiantesDB?retryWrites=true&w=majority&appName=Cluster0
    nodeVersion: 18
